version: "3.4"

services:
  healthchecks:
    image: linuxserver/healthchecks
    container_name: healthchecks
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - SITE_ROOT=http://${LOCAL_DOMAIN}:9320
      - SITE_NAME=Health Checks
      - SUPERUSER_EMAIL=${ADMIN_EMAIL}
      - SUPERUSER_PASSWORD=${ADMIN_PASSWORD}
      - APPRISE_ENABLED=True
      - PING_BODY_LIMIT=100000
      - DEBUG=False
    volumes:
      - ${DOCKER_APP_DATA}/healthchecks:/config
    ports:
      - 9320:8000
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.healthchecks.rule=Host(`healthchecks.${INET_DOMAIN}`)
      - traefik.http.routers.healthchecks.tls=true
      - traefik.http.routers.healthchecks.tls.certresolver=letsencrypt
      - flame.type=app
      - flame.name=Health Checks
      - flame.url=https://healthchecks.${INET_DOMAIN}
      - flame.icon=bottle-tonic-plus