version: '3.4'

services:
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    restart: unless-stopped
    volumes:
      - ${DOCKER_APP_DATA}/uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: host
    labels:
      - flame.type=app
      - flame.name=Uptime Kuma
      - flame.url=http://${LOCAL_DOMAIN}:3001
      - flame.icon=list-status
