version: "3.4"

services:
  samba:
    container_name: samba
    image: dperson/samba
    environment:
      TZ: "UTC"
      USERID: 1000
      GROUPID: 1000
    networks:
      - default
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - ${PRIMARY_STORAGE}:/mnt/primary:z
      - ${SECONDARY_STORAGE}:/mnt/secondary:z
      - ${PRIMARY_BACKUP_STORAGE}:/mnt/primary-backup:z
    command: '-s "primary;/mnt/primary;yes;no;yes;all;all;all" -s "secondary;/mnt/secondary;yes;no;yes;all;all;all" -s "primary-backup;/mnt/primary-backup;yes;no;yes;all;all;all" -u "${ADMIN_USERNAME};${ADMIN_PASSWORD}" -g "inherit permissions = yes" -g "directory mask = 02775" -g "force directory mode = 02775"'
