version: "3.9"

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Etc/UTC
    volumes:
      - ${DOCKER_APP_DATA}/jellyfin/config:/config
      - ${SECONDARY_STORAGE}/downloads/media/tv:/tv
      - ${SECONDARY_STORAGE}/downloads/media/movies:/movies
      - ${SECONDARY_STORAGE}/downloads/media/music:/music
      - ${PRIMARY_STORAGE}/media:/media
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
    labels:
      - flame.type=app
      - flame.name=Jellyfin
      - flame.url=http://${LOCAL_DOMAIN}:8096
      - flame.icon=plex