#!/bin/bash

export COMPOSE_FILES="$(find . | grep "compose.yml")"
export CRONTAB_FILES="$(find . | grep "crontab")"

# Start all Docker (compose) containers
for COMPOSE_FILE in $COMPOSE_FILES
do
    docker-compose -f $COMPOSE_FILE --env-file $ENV_FILE up -d --build --remove-orphans
done

# Re-create all Crontab
echo "# Do not edit this file. Auto created in personal-cloud/start-all.sh" >> tmp_crontab
echo "SHELL=/bin/bash" >> tmp_crontab
echo "$(grep -v '^#' /mnt/primary/workspace/.env)" >> tmp_crontab

for CRONTAB_FILE in $CRONTAB_FILES
do
    echo "# From $CRONTAB_FILE:" >> tmp_crontab
    cat $CRONTAB_FILE >> tmp_crontab
    printf "\n" >> tmp_crontab
done

crontab tmp_crontab
rm tmp_crontab
crontab -l
