version: "3.4"

services:
  scanservjs:
    container_name: scanservjs
    image: sbs20/scanservjs
    ports:
      - 8888:8080
    user: 2001:1000
    volumes:
      - /var/run/dbus:/var/run/dbus
      - /dev/bus/usb/001/001:/dev/bus/usb/001/001
      - /dev/bus/usb/001/002:/dev/bus/usb/001/002
      - /dev/bus/usb/001/003:/dev/bus/usb/001/003
      - /dev/bus/usb/001/004:/dev/bus/usb/001/004
      - /dev/bus/usb/002/001:/dev/bus/usb/002/001
      - /dev/bus/usb/002/002:/dev/bus/usb/002/002
      - /dev/bus/usb/002/003:/dev/bus/usb/002/003
      - /dev/bus/usb/002/003:/dev/bus/usb/002/004
      - ${PRIMARY_STORAGE}/docs/scan-output:/app/data/output
    privileged: true
    restart: unless-stopped
    labels:
      - flame.type=app
      - flame.name=Scanservjs
      - flame.url=http://${LOCAL_DOMAIN}:8888
      - flame.icon=scanner
