version: "3.4"

services:
  flame:
    image: pawelmalak/flame
    container_name: flame
    volumes:
      - ${DOCKER_APP_DATA}/flame:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 5005:5005
    environment:
      - PASSWORD=${ADMIN_PASSWORD}
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.flame.rule=Host(`start.${INET_DOMAIN}`)
      - traefik.http.routers.flame.tls=true
      - traefik.http.routers.flame.tls.certresolver=letsencrypt
