version: "3.4"

services:
  flame:
    image: pawelmalak/flame
    container_name: flame
    volumes:
      - ${DOCKER_APP_DATA}/flame:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:5005
    environment:
      - PASSWORD=${ADMIN_PASSWORD}
    restart: unless-stopped
