version: "3.4"

services:
  traefik:
    container_name: traefik
    image: traefik:v2.5
    network_mode: host
    restart: unless-stopped
    environment:
      INET_DOMAIN: ${INET_DOMAIN}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
    volumes:
      - ${PERSONAL_CLOUD_DIR}/traefik/traefik.yml:/etc/traefik/traefik.yml
      - ${PERSONAL_CLOUD_DIR}/traefik/homeassistant.traefik.yml:/etc/traefik/homeassistant.traefik.yml
      - ${DOCKER_APP_DATA}/traefik/letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - flame.type=app
      - flame.name=Traefik
      - flame.url=http://${LOCAL_DOMAIN}:8080
      - flame.icon=lock
