version: "3.4"

services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=docker
    volumes:
      - ${DOCKER_APP_DATA}/plex:/config
      - ${SECONDARY_STORAGE}/downloads/media/tv:/tv
      - ${SECONDARY_STORAGE}/downloads/media/movies:/movies
      - ${SECONDARY_STORAGE}/downloads/media/music:/music
      - ${PRIMARY_STORAGE}/media:/media
    restart: unless-stopped
    labels:
      - flame.type=app
      - flame.name=Plex
      - flame.url=http://${LOCAL_DOMAIN}:32400
      - flame.icon=plex