version: "3.4"

services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=docker
    volumes:
      - ${DOCKER_APP_DATA}/plex:/config
      - ${SECONDARY_STORAGE}/downloads/media/tv:/tv
      - ${SECONDARY_STORAGE}/downloads/media/movies:/movies
      - ${SECONDARY_STORAGE}/downloads/media/music:/music
      - ${SECONDARY_STORAGE}/media:/media
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.plex.rule=Host(`media.${INET_DOMAIN}`)
      - traefik.http.routers.plex.tls=true
      - traefik.http.routers.plex.tls.certresolver=letsencrypt
      - traefik.http.services.plex.loadbalancer.server.port=32400
      - flame.type=app
      - flame.name=Plex
      - flame.url=https://media.${INET_DOMAIN}
      - flame.icon=plex