version: "3.4"

services:
  wg-easy:
    container_name: wg-easy
    image: weejewel/wg-easy
    environment:
      - PASSWORD=${ADMIN_PASSWORD}
      - WG_HOST=jupiter.kajam.uk
      - WG_DEFAULT_DNS=192.168.1.1
      # - WG_PORT=51820
      # - WG_DEFAULT_ADDRESS=10.8.0.x
      # - WG_MTU=1420
      # - WG_ALLOWED_IPS=192.168.15.0/24, 10.0.1.0/24
    volumes:
      - ${DOCKER_APP_DATA}/wireguard:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    labels:
      - flame.type=app
      - flame.name=Wireguard
      - flame.url=http://${LOCAL_DOMAIN}:51821
      - flame.icon=vpn
