# This is needed instead of the docker labels
# due to the Home Assistant container having network_mode: host

http:
  routers:
    homeassistant:
      rule: "Host(`homeassistant.{{env "INET_DOMAIN" }}`)"
      tls:
        certresolver: letsencrypt
      entrypoints:
        - web
        - websecure
      service: homeassistant-svc
  services:
    homeassistant-svc:
      loadBalancer:
        servers:
          - url: "http://localhost:8123"
