providers:
  docker:
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.${INET_DOMAIN}`)"
    exposedByDefault: false
  file:
    filename: /etc/traefik/homeassistant.traefik.yml

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: ${ADMIN_EMAIL}
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web

api:
  insecure: true
