version: "3.4"

services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    cap_add:
      - net_admin
      - net_raw
      - NET_ADMIN
      - SYS_ADMIN
    volumes:
      - ${DOCKER_APP_DATA}/homeassistant:/config
      - ${PRIMARY_STORAGE}:/mnt/primary:z
      - ${SECONDARY_STORAGE}:/mnt/secondary:z
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    labels:
      - flame.type=app
      - flame.name=Home Assistant
      - flame.url=https://homeassistant.${INET_DOMAIN}
      - flame.icon=home