version: "3.4"

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - ${DOCKER_APP_DATA}/open-webui:/app/backend/data
    ports:
      - 3597:8080
    environment:
      - OPENAI_API_KEY=${OPEN_AI_KEY}
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    labels:
      - flame.type=app
      - flame.name=Open WebUI
      - flame.url=http://${LOCAL_DOMAIN}:3597
