version: "3.4"

services:
  syncthing:
    container_name: syncthing
    image: linuxserver/syncthing
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 8384:8384
      - 22000:22000
      - 21027:21027/udp
    volumes:
      - ${DOCKER_APP_DATA}/syncthing:/config
      - ${PRIMARY_STORAGE}:/mnt/primary:z
    restart: unless-stopped
    labels:
      - flame.type=app
      - flame.name=Syncthing
      - flame.url=http://${LOCAL_DOMAIN}:8384
      - flame.icon=cloud-sync