version: '3.1'

services:
  wordpress:
    container_name: wordpress
    image: wordpress
    restart: unless-stopped
    ports:
      - 6543:80
    environment:
      WORDPRESS_DB_HOST: wordpress-db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: ${SQL_PASSWORD}
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ${DOCKER_APP_DATA}/wordpress/html:/var/www/html
    labels:
      - traefik.enable=true
      - traefik.http.routers.story.rule=Host(`story.${INET_DOMAIN}`)
      - traefik.http.routers.story.tls=true
      - traefik.http.routers.story.tls.certresolver=letsencrypt
      - traefik.http.routers.story.middlewares=story-auth
      - "traefik.http.middlewares.story-auth.basicauth.users=apollo:${HTTP_PASSWORD}"
      - flame.type=app
      - flame.name=Our Story
      - flame.url=https://story.${INET_DOMAIN}
      - flame.icon=human-male-female-child

  wordpress-db:
    container_name: wordpress-db
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: ${SQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ${DOCKER_APP_DATA}/wordpress/data:/var/lib/mysql
