version: "3.4"

services:
  mariadb:
    image: ghcr.io/linuxserver/mariadb:latest
    container_name: lychee_mariadb
    restart: unless-stopped
    volumes:
      - ${DOCKER_APP_DATA}/lychee/db:/config
    environment:
      - MYSQL_ROOT_PASSWORD=${SQL_PASSWORD}
      - MYSQL_DATABASE=lychee
      - MYSQL_USER=lychee
      - MYSQL_PASSWORD=${SQL_PASSWORD}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  lychee:
    image: ghcr.io/linuxserver/lychee:latest
    container_name: lychee
    restart: unless-stopped
    depends_on:
      - mariadb
    volumes:
      - ${DOCKER_APP_DATA}/lychee/config:/config
      - ${PRIMARY_STORAGE}/media/photos:/pictures
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=lychee
      - DB_PASSWORD=${SQL_PASSWORD}
      - DB_DATABASE=lychee
      - DB_PORT=3306
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 8435:80
    labels:
      - traefik.enable=true
      - traefik.http.routers.lychee.rule=Host(`photos2.${INET_DOMAIN}`)
      - traefik.http.routers.lychee.tls=true
      - traefik.http.routers.lychee.tls.certresolver=letsencrypt
