version: "3.4"
services:
  apprise-api:
    image: linuxserver/apprise-api
    container_name: apprise-api
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_APP_DATA}/apprise:/config
    ports:
      - 2930:8000
    restart: unless-stopped
    labels:
      - flame.type=app
      - flame.name=Apprise
      - flame.url=http://${LOCAL_DOMAIN}:2930
      - flame.icon=android-messages