version: "3.4"

services:
  home-nginx:
    container_name: home-nginx
    image: nginx
    volumes:
      - ${PERSONAL_CLOUD_DIR}/home-tracker:/usr/share/nginx/html:z
      - ${PERSONAL_CLOUD_DIR}/home-tracker/mime.types:/etc/nginx/mime.types
    ports:
      - 4400:80
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.home-nginx.rule=Host(`home.${INET_DOMAIN}`)
      - traefik.http.routers.home-nginx.tls=true
      - traefik.http.routers.home-nginx.tls.certresolver=letsencrypt