version: "3.4"

services:
  ntfy:
    container_name: ntfy
    image: binwiederhier/ntfy
    command:
      - serve
    environment:
      - TZ=UTC
    volumes:
      - ${DOCKER_APP_DATA}/ntfy/cache:/var/cache/ntfy
      - ${DOCKER_APP_DATA}/ntfy/config:/etc/ntfy
    ports:
      - 2393:80
    restart: unless-stopped
    labels:
      - flame.type=app
      - flame.name=Ntfy
      - flame.url=http://${LOCAL_DOMAIN}:2393
      - flame.icon=bell
