version: "3.4"

services:
  node-red:
    container_name: node-red
    image: nodered/node-red:latest
    environment:
      - TZ=${TZ}
    ports:
      - "1880:1880"
    volumes:
      - ${DOCKER_APP_DATA}/node-red:/data
      - ${PERSONAL_CLOUD_DIR}/home-tracker:/home-tracker:z
    restart: unless-stopped
    labels:
      - flame.type=app
      - flame.name=NodeRED
      - flame.url=http://${LOCAL_DOMAIN}:1880
      - flame.icon=format-text-wrapping-overflow