version: "3.4"

services:
  portainer:
    container_name: portainer
    image: "portainer/portainer-ce:latest"
    ports:
      - "8000:8000"
      - "9090:9000"
      - "9443:9443"
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_APP_DATA}/portainer:/data
    networks:
      - portainer
    labels:
      - flame.type=app
      - flame.name=Portainer
      - flame.url=http://${LOCAL_DOMAIN}:9090
      - flame.icon=docker

networks:
  portainer: