version: "3.4"

services:
  motioneye:
    container_name: motioneye
    image: ccrisan/motioneye:master-amd64
    volumes:
      - ${DOCKER_APP_DATA}/motioneye:/etc/motioneye
      - ${PRIMARY_STORAGE}/media/cctv:/cctv:z
    restart: unless-stopped
    network_mode: host
    labels:
      - flame.type=app
      - flame.name=Motioneye
      - flame.url=http://${LOCAL_DOMAIN}:8765
      - flame.icon=cctv