version: "3"

services:
  traefik:
    image: traefik
    container_name: traefik
    restart: unless-stopped
    command:
      - "--api.dashboard=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=${ADMIN_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "${DOCKER_APP_DATA}/letsencrypt:/letsencrypt"
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${INET_DOMAIN}`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik.service=api@internal"

  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    restart: unless-stopped
    volumes:
      - ${DOCKER_APP_DATA}/uptime-kuma:/app/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.uptime.rule=Host(`uptime.${INET_DOMAIN}`)
      - traefik.http.routers.uptime.entrypoints=websecure
      - traefik.http.routers.uptime.tls=true
      - traefik.http.routers.uptime.tls.certresolver=letsencrypt
    networks:
      - web

  healthchecks:
    image: linuxserver/healthchecks
    container_name: healthchecks
    environment:
      - TZ=Europe/London
      - SITE_ROOT=https://healthchecks.${INET_DOMAIN}
      - SITE_NAME=Health Checks
      - SUPERUSER_EMAIL=${ADMIN_EMAIL}
      - SUPERUSER_PASSWORD=${ADMIN_PASSWORD}
      - APPRISE_ENABLED=True
      - PING_BODY_LIMIT=100000
      - DEBUG=False
    restart: unless-stopped
    volumes:
      - ${DOCKER_APP_DATA}/healthchecks:/config
    labels:
      - traefik.enable=true
      - traefik.http.routers.healthchecks.rule=Host(`healthchecks.${INET_DOMAIN}`)
      - traefik.http.routers.healthchecks.entrypoints=websecure
      - traefik.http.routers.healthchecks.tls=true
      - traefik.http.routers.healthchecks.tls.certresolver=letsencrypt
    networks:
      - web

  syncthing:
    container_name: syncthing
    image: linuxserver/syncthing
    environment:
      - TZ=Europe/London
    ports:
      - 22000:22000
      - 21027:21027/udp
    volumes:
      - ${DOCKER_APP_DATA}/syncthing:/config
      - ${DOCKER_APP_DATA}/data:/data
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.syncthing.rule=Host(`sync.${INET_DOMAIN}`)
      - traefik.http.routers.syncthing.entrypoints=websecure
      - traefik.http.routers.syncthing.tls=true
      - traefik.http.routers.syncthing.tls.certresolver=letsencrypt
      - traefik.http.routers.syncthing.service=syncthing
      - traefik.http.services.syncthing.loadbalancer.server.port=8384
    networks:
      - web

networks:
  web:
    driver: bridge
