version: "3.4"

services:
  db_recipes:
    container_name: db_recipes
    restart: unless-stopped
    image: postgres:11-alpine
    volumes:
      - ${DOCKER_APP_DATA}/tandoor/db:/var/lib/postgresql/data
    env_file:
      - ./.tandoor.env

  web_recipes:
    container_name: web_recipes
    image: vabene1111/recipes
    env_file:
      - ./.tandoor.env
    volumes:
      - ${DOCKER_APP_DATA}/tandoor/static:/opt/recipes/staticfiles
      - ${DOCKER_APP_DATA}/tandoor/nginx:/opt/recipes/nginx/conf.d
      - ${DOCKER_APP_DATA}/tandoor/media:/opt/recipes/mediafiles
    ports:
      - 6789:8080
    depends_on:
      - db_recipes
    restart: unless-stopped

  nginx_recipes:
    container_name: nginx_recipes
    image: nginx:mainline-alpine
    restart: unless-stopped
    env_file:
      - ./.tandoor.env
    ports:
      - 4001:80
    volumes:
      - ${DOCKER_APP_DATA}/tandoor/nginx:/etc/nginx/conf.d:ro
      - ${DOCKER_APP_DATA}/tandoor/static:/static
      - ${DOCKER_APP_DATA}/tandoor/media:/media
    labels:
      - traefik.enable=true
      - traefik.http.routers.recipes.rule=Host(`recipes.${INET_DOMAIN}`)
      - traefik.http.routers.recipes.tls=true
      - traefik.http.routers.recipes.entrypoints=websecure
      - traefik.http.routers.recipes.tls.certresolver=letsencrypt
    depends_on:
      - web_recipes